### ISSUE TITLE
config should handle lower and upper case checks

### ISSUE THREAD

**Issue by hemz10** [HugoByte/polkadot-kurtosis-package#79]
## Overview
Currently the package accepts only lower case letters, when passing upper case it throws an error. 

## Steps to Reproduce
1.In the config json file give the chain name in upper case
2. Observe the output

## Expected Behavior
It should internally convert to lower case and continue with execution. execution should not stop

## Screenshots
![image](https://github.com/HugoByte/polakadot-kurtosis-package/assets/96766939/536697af-b5e2-46ca-ad53-58283811d3c4)

**Comment by Mr-Nobody21** [comment]
Fixed in pr #176

**Comment by hemz10** [comment]
Closing this issue as fixed
